spring:
  application:
    name: GearGrove

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: aziteror50957@gmail.com
    password: rrzgvvsenhhbfjif
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

geargrove:
  login:
    datasource:
      url: jdbc:postgresql://localhost:5432/Gear_Grove_Users
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  products:
    datasource:
      url: jdbc:postgresql://localhost:5432/Gear_Grove_Products
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  orders:
    datasource:
      url: jdbc:postgresql://localhost:5432./Gear_Grove_Orders
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver



jwt:
  user_secret: s2v6asadsas1fsde1CSsaf2rewfas902u0aJWsgGIQ7382bfjafqfhqhfo
  user_secret_lifetime: 10m
