spring:
  application:
    name: GearGrove

  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

geargrove:
  login:
    datasource:
      url: jdbc:postgresql://localhost:5432/Gear_Grove_Users
      username: postgres
      password: 28859013
      driver-class-name: org.postgresql.Driver
  products:
    datasource:
      url: jdbc:postgresql://localhost:5432/Gear_Grove_Products
      username: postgres
      password: 28859013
      driver-class-name: org.postgresql.Driver
  orders:
    datasource:
      url: jdbc:postgresql://localhost:5432/Gear_Grove_Orders
      username: postgres
      password: 28859013
      driver-class-name: org.postgresql.Driver
  reviews:
    datasource:
      url: jdbc:postgresql://localhost:5432/Gear_Grove_Reviews
      username: postgres
      password: 28859013
      driver-class-name: org.postgresql.Driver


jwt:
  user_secret: s2v6asadsas1fsde1CSsaf2rewfas902u0aJWsgGIQ7382bfjafqfhqhfo
  user_secret_lifetime: 10m
